// Shared site header - generated by Nemax CMS. Edit the menu at http://localhost:5077/menu
document.currentScript.insertAdjacentHTML('beforebegin', `<style>
  .navbar .dropdown-icon svg {
    display: block;
  }

  .sub-dropdown {
    position: relative;
    display: block;
    width: 100%;
  }

  .sub-dropdown>.dropdown-toggle {
    display: flex;
    align-items: center;
    justify-content: space-between;
    width: 100%;
    white-space: nowrap;
  }

  .sub-dropdown .dropdown-icon {
    position: static;
    width: auto;
    height: auto;
    margin: 0 0 0 8px;
  }

  .sub-dropdown>.w-dropdown-list {
    top: 0;
    left: 100%;
    margin-top: 0;
  }

  @media (max-width: 991px) {
    /* template CSS hides dropdown labels in the mobile menu - restore them */
    .navbar .dropdown-toggle.nav-link > div:last-child {
      display: inline-flex !important;
      align-items: center;
    }

    .nav-list > .dropdown > .dropdown-toggle {
      display: flex;
      align-items: center;
      gap: 8px;
      padding-top: 10px;
      padding-bottom: 10px;
    }

    .nav-list > .dropdown > .dropdown-toggle > .dropdown-icon {
      position: static;
      margin: 0;
      order: 2;
    }

    .nav-list .w-dropdown-list.w--open {
      position: static;
      width: 100%;
    }

    .sub-dropdown>.w-dropdown-list {
      position: static;
    }
  }
</style>
<div class="navbar w-nav" data-animation="default" data-collapse="medium" data-doc-height="1" data-duration="400"
  data-easing="ease" data-easing2="ease" data-wf--navbar--variant="base" role="banner">
  <div class="container w-container">
    <div class="w-layout-grid grid-nav">
      <div class="navbar-left" id="w-node-dd71c13d-d886-0748-770b-251bd9cafd66-18a8ef3c">
        <div class="navbar-left-wrap"><a class="brand w-nav-brand" href="index.html"><img alt="Nemax AI Logo"
              class="logo" loading="lazy" src="assets/Nemax AI Logo Main.png" /></a>
        </div>
      </div>
      <div class="navbar-gap"></div>
      <div class="nav-center-item" id="w-node-f2b3a5ba-20d8-3a08-66b7-980227151626-18a8ef3c">
        <div class="navbar-center">
          <nav class="nav-menu w-nav-menu" role="navigation">
            <div class="nav-list">
              <a class="nav-link w-nav-link" href="index.html">Home</a>
              <a class="nav-link w-nav-link" href="about.html">About</a>
              <a class="nav-link w-nav-link" href="pricing.html">Pricing</a>
              <a class="nav-link w-nav-link" href="contact.html">Contact</a>
              <div class="dropdown w-dropdown" data-delay="0" data-hover="true"><div class="dropdown-toggle nav-link w-dropdown-toggle"><div class="dropdown-icon w-icon-dropdown-toggle"><svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="6 9 12 15 18 9"></polyline></svg></div><div>More</div></div><nav class="dropdown-list w-dropdown-list"><div class="dropdown-link-list"><a class="dropdown-link w-dropdown-link" href="privacy-policy.html">Privacy Policy</a></div></nav></div>
            </div>
          </nav>
        </div>
      </div>
      <div class="navbar-gap"></div>
      <div class="navbar-right" id="w-node-e6ff9f79-f479-fa42-6f69-a3df18a8ef64-18a8ef3c">
        <div class="navbar-right-wrap"><a aria-label="Email" class="nav-right-item w-inline-block"
            data-w-id="4c822d0e-90f6-ba53-b06e-7d295892bf2b" href="#" data-js-em="1">
            <div class="nav-right-wrap"><img alt="Email icon" class="nav-right-image" loading="lazy"
                src="assets/icons/xLIkjgcmFOsC.webp" /><img alt="Email icon"
                class="nav-right-hover" loading="lazy"
                src="assets/icons/xLIkjgcmFOsC.webp" />
            </div>
          </a><a aria-label="Let's talk" class="nav-right-item w-inline-block"
            data-w-id="a7aaeaed-6063-800b-7fef-f4177899d80a" href="https://calendly.com/nemaxaiofficial/30min">
            <div class="nav-right-wrap"><img alt="Calendar icon" class="nav-right-image" loading="lazy"
                src="assets/icons/letUS1DJO1ou.webp" /><img
                alt="Calendar icon" class="nav-right-hover" loading="lazy"
                src="assets/icons/letUS1DJO1ou.webp" />
            </div>
          </a>
          <div class="menu-button w-nav-button">
            <div class="menu-icon w-icon-nav-menu"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>`);
